// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToCBooks.App.Data.Context;

namespace ToCBooks.App.Migrations
{
    [DbContext(typeof(ToCBooksContext))]
    [Migration("20200909000537_Atualizacao07")]
    partial class Atualizacao07
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToCBooks.App.Business.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Justificativa")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<Guid?>("LivrosModelId");

                    b.Property<string>("NomeCategoria")
                        .HasColumnType("VARCHAR(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("LivrosModelId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.CidadeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EstadoId");

                    b.Property<string>("Justificativa");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("CidadeModel");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.ClienteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<string>("Email");

                    b.Property<Guid?>("EnderecoCobrancaId");

                    b.Property<Guid?>("EnderecoEntregaId");

                    b.Property<string>("Justificativa");

                    b.Property<string>("Nome");

                    b.Property<string>("Observacao");

                    b.Property<string>("Senha");

                    b.Property<int?>("TelefoneId");

                    b.Property<int>("TipoGenero");

                    b.Property<int>("TipoUsuario");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoCobrancaId");

                    b.HasIndex("EnderecoEntregaId");

                    b.HasIndex("TelefoneId");

                    b.ToTable("ClienteModel");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.EnderecoCobrancaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<int>("CEP");

                    b.Property<Guid?>("CidadeId");

                    b.Property<string>("Justificativa");

                    b.Property<string>("Nome");

                    b.Property<int>("Numero");

                    b.Property<int>("TipoLogradouro");

                    b.Property<int>("TipoResidencia");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("EnderecoCobrancaModel");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.EnderecoEntregaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<int>("CEP");

                    b.Property<Guid?>("CidadeId");

                    b.Property<string>("Justificativa");

                    b.Property<string>("Nome");

                    b.Property<int>("Numero");

                    b.Property<int>("TipoLogradouro");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("EnderecoEntregaModel");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.EstadoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Justificativa");

                    b.Property<string>("Nome");

                    b.Property<Guid?>("PaisId");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("EstadoModel");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.LivrosModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Altura");

                    b.Property<int>("Ano");

                    b.Property<string>("Autor")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("CodigoDeBarras")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Edicao");

                    b.Property<string>("Editora")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("Foto")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("ISBN")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("Justificativa")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<double>("Largura");

                    b.Property<int>("Paginas");

                    b.Property<double>("Peso");

                    b.Property<Guid?>("PrecificacaoId");

                    b.Property<string>("Preco")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 64)))
                        .HasColumnType("varchar(200)");

                    b.Property<double>("Profundidade");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PrecificacaoId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.PaisModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Justificativa");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("PaisModel");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.Parametro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Justificativa")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("Nome")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<int>("Tipo");

                    b.Property<double>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Parametro");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.TelefoneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DDD");

                    b.Property<int>("Numero");

                    b.Property<int>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("TelefoneModel");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.Categoria", b =>
                {
                    b.HasOne("ToCBooks.App.Business.Models.LivrosModel")
                        .WithMany("Categorias")
                        .HasForeignKey("LivrosModelId");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.CidadeModel", b =>
                {
                    b.HasOne("ToCBooks.App.Business.Models.EstadoModel", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.ClienteModel", b =>
                {
                    b.HasOne("ToCBooks.App.Business.Models.EnderecoCobrancaModel", "EnderecoCobranca")
                        .WithMany()
                        .HasForeignKey("EnderecoCobrancaId");

                    b.HasOne("ToCBooks.App.Business.Models.EnderecoEntregaModel", "EnderecoEntrega")
                        .WithMany()
                        .HasForeignKey("EnderecoEntregaId");

                    b.HasOne("ToCBooks.App.Business.Models.TelefoneModel", "Telefone")
                        .WithMany()
                        .HasForeignKey("TelefoneId");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.EnderecoCobrancaModel", b =>
                {
                    b.HasOne("ToCBooks.App.Business.Models.CidadeModel", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.EnderecoEntregaModel", b =>
                {
                    b.HasOne("ToCBooks.App.Business.Models.CidadeModel", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.EstadoModel", b =>
                {
                    b.HasOne("ToCBooks.App.Business.Models.PaisModel", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId");
                });

            modelBuilder.Entity("ToCBooks.App.Business.Models.LivrosModel", b =>
                {
                    b.HasOne("ToCBooks.App.Business.Models.Parametro", "Precificacao")
                        .WithMany()
                        .HasForeignKey("PrecificacaoId");
                });
#pragma warning restore 612, 618
        }
    }
}
